---
title: "Visualization of benchmarking results"
---

# Packages
```{r}
library(reshape2)
library(ggplot2)
library(ggsci)
if(!require(patchwork))
{install.packages("patchwork")}
library(patchwork)
```
# set directory

```{r}
dir <- "/data/analysis/data/Figure 1 - Overview/"
```

# Condor vs. Catalyst

## Prepare cCONDOR output data
```{r}
#load cyCONDOR data
load("../data/2024-04-30_cyCONDOR_flowSOM_Benchmark.RData")
```

```{r}
time_100_vector <- c()

for (i in 1:length(time_100)) {
  
  tmp <- time_100[[i]]
  
  tmp <- tmp$toc - tmp$tic
  
  time_100_vector <- c(time_100_vector, tmp)
  
}

time_1000_vector <- c()

for (i in 1:length(time_1000)) {
  
  tmp <- time_1000[[i]]
  
  tmp <- tmp$toc - tmp$tic
  
  time_1000_vector <- c(time_1000_vector, tmp)
  
}

time_10000_vector <- c()

for (i in 1:length(time_10000)) {
  
  tmp <- time_10000[[i]]
  
  tmp <- tmp$toc - tmp$tic
  
  time_10000_vector <- c(time_10000_vector, tmp)
  
}

time_100000_vector <- c()

for (i in 1:length(time_100000)) {
  
  tmp <- time_100000[[i]]
  
  tmp <- tmp$toc - tmp$tic
  
  time_100000_vector <- c(time_100000_vector, tmp)
  
}

time_1000000_vector <- c()

for (i in 1:length(time_1000000)) {
  
  tmp <- time_1000000[[i]]
  
  tmp <- tmp$toc - tmp$tic
  
  time_1000000_vector <- c(time_1000000_vector, tmp)
  
}

rm(i)
```

```{r}
bm_data <- data.frame(time_100 = time_100_vector,
                      time_1000 = time_1000_vector,
                      time_10000 = time_10000_vector,
                      time_100000 = time_100000_vector,
                      time_1000000 = time_1000000_vector)

bm_melt <- melt(bm_data, value.name = "time")

bm_melt$cell_count <- as.numeric(sapply(strsplit(as.character(bm_melt$variable), "_"), function(x){return(x[[2]])}))
```


```{r}
# add workflow info
bm_melt$workflow <- "cyCONDOR"
bm_melt
```
## Prepare CATALYST output data
```{r}
#load data
load("../data/2024-04-29_CATALYST_Benchmark.RData")
```

```{r}
time_100_vector <- c()

for (i in 1:length(time_100)) {
  
  tmp <- time_100[[i]]
  
  tmp <- tmp$toc - tmp$tic
  
  time_100_vector <- c(time_100_vector, tmp)
  
}

time_1000_vector <- c()

for (i in 1:length(time_1000)) {
  
  tmp <- time_1000[[i]]
  
  tmp <- tmp$toc - tmp$tic
  
  time_1000_vector <- c(time_1000_vector, tmp)
  
}

time_10000_vector <- c()

for (i in 1:length(time_10000)) {
  
  tmp <- time_10000[[i]]
  
  tmp <- tmp$toc - tmp$tic
  
  time_10000_vector <- c(time_10000_vector, tmp)
  
}

time_100000_vector <- c()

for (i in 1:length(time_100000)) {
  
  tmp <- time_100000[[i]]
  
  tmp <- tmp$toc - tmp$tic
  
  time_100000_vector <- c(time_100000_vector, tmp)
  
}

time_1000000_vector <- c()

for (i in 1:length(time_1000000)) {
  
  tmp <- time_1000000[[i]]
  
  tmp <- tmp$toc - tmp$tic
  
  time_1000000_vector <- c(time_1000000_vector, tmp)
  
}

rm(i)
```

```{r}
bm_data_catalyst <- data.frame(time_100 = time_100_vector,
                      time_1000 = time_1000_vector,
                      time_10000 = time_10000_vector,
                      time_100000 = time_100000_vector,
                      time_1000000 = time_1000000_vector)

bm_melt_catalyst <- melt(bm_data_catalyst, value.name = "time")

bm_melt_catalyst$cell_count <- as.numeric(sapply(strsplit(as.character(bm_melt_catalyst$variable), "_"), function(x){return(x[[2]])}))
```
```{r}
# add workflow info
bm_melt_catalyst$workflow <- "CATALYST"
```



```{r}
input <- rbind(bm_melt, bm_melt_catalyst)
```

```{r}
rm(condor, sce, A)
```


## Plotting
```{r}
ggplot(input, aes(x = cell_count, y = time, color = workflow)) +
  geom_jitter(size = 3) +
  scale_x_log10() +
  scale_y_log10() +
  scale_color_aaas() +
  theme_bw() + theme(aspect.ratio = 1)
```


# cyCONDOR vs. SPECTRE

## Prepare cyCONDOR output data
```{r}
#load cyCONDOR data
load("../data/2024-04-12_cyCONDOR_Benchmark.RData")
```

```{r}
time_100_vector <- c()

for (i in 1:length(time_100)) {
  
  tmp <- time_100[[i]]
  
  tmp <- tmp$toc - tmp$tic
  
  time_100_vector <- c(time_100_vector, tmp)
  
}

time_1000_vector <- c()

for (i in 1:length(time_1000)) {
  
  tmp <- time_1000[[i]]
  
  tmp <- tmp$toc - tmp$tic
  
  time_1000_vector <- c(time_1000_vector, tmp)
  
}

time_10000_vector <- c()

for (i in 1:length(time_10000)) {
  
  tmp <- time_10000[[i]]
  
  tmp <- tmp$toc - tmp$tic
  
  time_10000_vector <- c(time_10000_vector, tmp)
  
}

time_100000_vector <- c()

for (i in 1:length(time_100000)) {
  
  tmp <- time_100000[[i]]
  
  tmp <- tmp$toc - tmp$tic
  
  time_100000_vector <- c(time_100000_vector, tmp)
  
}

time_1000000_vector <- c()

for (i in 1:length(time_1000000)) {
  
  tmp <- time_1000000[[i]]
  
  tmp <- tmp$toc - tmp$tic
  
  time_1000000_vector <- c(time_1000000_vector, tmp)
  
}

rm(i)
```

```{r}
data_cyCONDOR <- data.frame(time_100 = time_100_vector,
                      time_1000 = time_1000_vector,
                      time_10000 = time_10000_vector,
                      time_100000 = time_100000_vector,
                      time_1000000 = time_1000000_vector)

data_cyCONDOR  <- melt(data_cyCONDOR , value.name = "time")

data_cyCONDOR$cell_count <- as.numeric(sapply(strsplit(as.character(data_cyCONDOR$variable), "_"), function(x){return(x[[2]])}))
```


```{r}
# add workflow info
data_cyCONDOR$workflow <- "cyCONDOR"
data_cyCONDOR 
```
## Prepare SPECTRE output data
```{r}
#loaddata
load("../data/2024-04-13_Spectre_Benchmark.RData")
```

```{r}
time_100_vector <- c()

for (i in 1:length(time_100)) {
  
  tmp <- time_100[[i]]
  
  tmp <- tmp$toc - tmp$tic
  
  time_100_vector <- c(time_100_vector, tmp)
  
}

time_1000_vector <- c()

for (i in 1:length(time_1000)) {
  
  tmp <- time_1000[[i]]
  
  tmp <- tmp$toc - tmp$tic
  
  time_1000_vector <- c(time_1000_vector, tmp)
  
}

time_10000_vector <- c()

for (i in 1:length(time_10000)) {
  
  tmp <- time_10000[[i]]
  
  tmp <- tmp$toc - tmp$tic
  
  time_10000_vector <- c(time_10000_vector, tmp)
  
}

time_100000_vector <- c()

for (i in 1:length(time_100000)) {
  
  tmp <- time_100000[[i]]
  
  tmp <- tmp$toc - tmp$tic
  
  time_100000_vector <- c(time_100000_vector, tmp)
  
}

time_1000000_vector <- c()

for (i in 1:length(time_1000000)) {
  
  tmp <- time_1000000[[i]]
  
  tmp <- tmp$toc - tmp$tic
  
  time_1000000_vector <- c(time_1000000_vector, tmp)
  
}

rm(i)
```

```{r}
data_SPECTRE <- data.frame(time_100 = time_100_vector,
                      time_1000 = time_1000_vector,
                      time_10000 = time_10000_vector,
                      time_100000 = time_100000_vector,
                      time_1000000 = time_1000000_vector)

data_SPECTRE  <- melt(data_SPECTRE , value.name = "time")

data_SPECTRE$cell_count <- as.numeric(sapply(strsplit(as.character(data_SPECTRE$variable), "_"), function(x){return(x[[2]])}))
```


```{r}
# add workflow info
data_SPECTRE$workflow <- "SPECTRE"
data_SPECTRE
```

```{r}
input_condor_spectre <- rbind(data_cyCONDOR, data_SPECTRE)
```



## Plotting
```{r}
ggplot(input_condor_spectre, aes(x = cell_count, y = time, color = workflow)) +
  geom_jitter(size = 3) +
  scale_x_log10() +
  scale_y_log10() +
  scale_color_aaas() +
  theme_bw() + theme(aspect.ratio = 1)
```



```{r, fig.height=5, fig.width=10}
p1 <- ggplot(input, aes(x = cell_count, y = time, color = workflow)) +
      geom_jitter(size = 3) +
      scale_x_log10() +
      scale_y_log10() +
    #  scale_color_aaas() +
      theme_bw() + theme(aspect.ratio = 1)+
      ggtitle("cyCONDOR vs. CATALYST")+
  scale_color_manual(values= c("red", "blue"))


p2 <- ggplot(input_condor_spectre, aes(x = cell_count, y = time, color = workflow)) +
  geom_jitter(size = 3) +
  scale_x_log10() +
  scale_y_log10() +
 # scale_color_aaas() +
  theme_bw() + theme(aspect.ratio = 1)+
   ggtitle("cyCONDOR vs. SPECTRE")+
  scale_color_manual(values= c("blue", "red"))

p1 + p2

# cairo_pdf("../figures/benchmarking_results_240502.pdf", height = 5, width = 10)
# p1 + p2
# dev.off()
```

