---
title: "Figure 4.1 - Pseudotime analysis workflow"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{condor_workflow}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  markdown: 
    wrap: 72
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(condor)
library(ggplot2)
library(ggsci)
library(dplyr)
library(ggpubr)
library(pheatmap)
```

# Loading the data

```{r}
condor <- prep_fcd(FCSpath = "./Data/CyTOF_BM/", 
                    ceil = 10000, 
                    useCSV = FALSE, 
                    transformation = "a", 
                    remove_param = c("Cell Length", "191-DNA", "193-DNA", "EventNum", "110-CD3", "111-CD3", "112-CD3", "113-CD3", "114-CD3", "InFile", "Time"), 
                    anno_table = "./data/Bendall_et_al_Science_2011_singlets.csv", 
                    filename_col = "filename",
                    seed = 91)
```

```{r}
class(condor)
```

# Dimensionality Reduction

## PCA
```{r}
condor <- runPCA(fcd = condor, 
                 data_slot = "orig", 
                 seed = 91)
```

## UMAP
```{r}
condor <- runUMAP(fcd = condor, 
                  input_type = "pca", 
                  data_slot = "orig", 
                  seed = 91)
```

# Clustering

## Phenograph
```{r}
condor <- runPhenograph(fcd = condor, 
                        input_type = "pca", 
                        data_slot = "orig", 
                        k = 10, 
                        seed = 91)
```

```{r}
plot_marker(data = cbind(condor$umap$pca_orig, condor$clustering$Phenograph_pca_orig_k_10), 
            param = "Phenograph", 
            order = T, 
            title = "Figure S5b - UMAP Phenograph clustering", 
            dim_red = "UMAP", 
            facet_by_variable = FALSE, dot_size = 0.2, apha = 1)
```

```{r, fig.height=7}
HM_markers(input = cbind(condor$expr$orig, condor$clustering$Phenograph_pca_orig_k_10), 
           group = "Phenograph",
           maxvalue = 2, 
           title = "Figure S5c - Marker expression Phenograph clustering", 
           cluster_rows = TRUE, cluster_cols = TRUE)
```

# Metaclustering
```{r}
condor <- metaclustering(fcd = condor, 
                         clustering = "Phenograph_pca_orig_k_10", 
                         name_col = "Phenograph", 
                         name_out = "metaclusters", 
                         metaclusters = c("1" = "Mature B cells IL3Ra+", 
                                          "2" = "Monoblast", 
                                          "3" = "Granulocytes", 
                                          "4" = "Platlets", 
                                          "5" = "Mature B cells IL3Ra+", 
                                          "6" = "Erytrocytes", 
                                          "7" = "CD8+ T cells", 
                                          "8" = "Monocytes", 
                                          "9" = "Mature B cells", 
                                          "10" = "Trombocytes", 
                                          "11" = "NK cells", 
                                          "12" = "CD4+ T cells", 
                                          "13" = "Erytroblast",
                                          "14" = "NKT",
                                          "15" = "Erytroblast",
                                          "16" = "HSCs",
                                          "17" = "DP T cells",
                                          "18" = "pDCs",
                                          "19" = "Immature B cells",
                                          "20" = "Monoblast",
                                          "21" = "CD4+ T cells",
                                          "22" = "Plasma cells",
                                          "23" = "Myelocytes",
                                          "24" = "Promyelocytes",
                                          "25" = "CD8+ T cells",
                                          "26" = "CD8+ T cells"))
```

```{r}
plot_marker(data = cbind(condor$umap$pca_orig, condor$clustering$Phenograph_pca_orig_k_10), 
            param = "metaclusters", 
            order = T, 
            title = "Figure 4b - UMAP Metaclusters", 
            dim_red = "UMAP", 
            facet_by_variable = FALSE, dot_size = 0.2, apha = 1)
```

# Subset the monocytes - pDCs lineages
```{r}
selections <- rownames(condor$clustering$Phenograph_pca_orig_k_10[condor$clustering$Phenograph_pca_orig_k_10$metaclusters %in% c("HSCs", "pDCs", "Monoblast", "Monocytes"), ])

condor_filter <- filter_fcd(fcdataset = condor,
                            cell_ids = selections)
```

## PCA
```{r}
condor_filter <- runPCA(fcd = condor_filter, 
                 data_slot = "orig", 
                 seed = 91)
```

## UMAP
```{r}
condor_filter <- runUMAP(fcd = condor_filter, 
                  input_type = "pca", 
                  data_slot = "orig", 
                  seed = 91)
```

# Clustering

## Phenograph
```{r}
condor_filter <- runPhenograph(fcd = condor_filter, 
                               input_type = "pca", 
                               data_slot = "orig", 
                               k = 10, 
                               seed = 91, 
                               prefix = "filter")
```

```{r}
## Remove contaminating cluster
selections <- rownames(condor_filter$clustering$Phenograph_filter_pca_orig_k_10[!condor_filter$clustering$Phenograph_filter_pca_orig_k_10$Phenograph %in% c("11"), ])

condor_filter <- filter_fcd(fcdataset = condor_filter,
                            cell_ids = selections)
```

```{r}
plot_marker(data = cbind(condor_filter$umap$pca_orig, condor_filter$anno$cell_anno, condor_filter$clustering$Phenograph_filter_pca_orig_k_10), 
            param = "Phenograph", 
            order = T, 
            title = "Figure S5d - UMAP by group", 
            dim_red = "UMAP", 
            facet_by_variable = FALSE, dot_size = 1, apha = 1)
```

# Metaclustering
```{r}
condor_filter <- metaclustering(fcd = condor_filter, 
                         clustering = "Phenograph_filter_pca_orig_k_10", 
                         name_col = "Phenograph", 
                         name_out = "metaclusters", 
                         metaclusters = c("1" = "Myelocytes", 
                                          "2" = "Monocytes", 
                                          "3" = "Monocytes", 
                                          "4" = "Monocytes", 
                                          "5" = "HSCs", 
                                          "6" = "Myeloblast", 
                                          "7" = "pDCs", 
                                          "8" = "CMPs", 
                                          "9" = "Monocytes", 
                                          "10" = "Pre-DC", 
                                          "11" = "CMPs", 
                                          "12" = "Myeloblast", 
                                          "13" = "Monocytes",
                                          "14" = "Monocytes",
                                          "15" = "Monocytes"))
```

```{r}
plot_marker(data = cbind(condor_filter$umap$pca_orig, condor_filter$anno$cell_anno, condor_filter$clustering$Phenograph_filter_pca_orig_k_10), 
            param = "metaclusters", 
            order = T, 
            title = "Figure 4c - UMAP by Phenograph", 
            dim_red = "UMAP", 
            facet_by_variable = FALSE, dot_size = 1, apha = 1)
```

```{r, fig.height=7}
HM_markers(input = cbind(condor_filter$expr$orig, condor_filter$clustering$Phenograph_filter_pca_orig_k_10), 
           group = "Phenograph",
           maxvalue = 2, 
           title = "Fig S5e - Marker expression Phenograph clustering", 
           cluster_rows = TRUE, cluster_cols = TRUE)
```

# Pseudotime analysis
```{r}
condor_filter <- runPseudotime(fcd = condor_filter, 
                               dim_red_type = "umap", 
                               dim_red_name = "pca_orig",
                               clustering = condor_filter$clustering$Phenograph_filter_pca_orig_k_10$metaclusters, 
                               approx_points = 5, 
                               seed = 91)
```

```{r}
plot_marker(data = cbind(condor_filter$umap$pca_orig, condor_filter$clustering$Phenograph_filter_pca_orig_k_10, condor_filter$pseudotime$slingshot_umap_pca_orig), 
                   param = "mean", 
                   order = T, 
                   title = "Figure 4e - UMAP mean pseudotime", 
                   dim_red = "UMAP", 
                   facet_by_variable = FALSE, dot_size = 1, apha = 1) + 
  geom_path(data = condor_filter$extras$slingshot_umap_pca_orig$lineages %>% arrange(Order), aes(group = Lineage), size = 0.5)
```

# Heatmap visualization of trajectory

## DCs
```{r}
selections <- rownames(condor_filter$clustering$Phenograph_filter_pca_orig_k_10[condor_filter$clustering$Phenograph_filter_pca_orig_k_10$metaclusters %in% c("HSCs", "Pre-DC", "pDCs"), ])

condor_dcs <- filter_fcd(fcdataset = condor_filter,
                            cell_ids = selections)
```

```{r}
expression <- condor_dcs$expr$orig

anno <- cbind(condor_dcs$clustering$Phenograph_filter_pca_orig_k_10[, c("Phenograph", "metaclusters")], condor_dcs$pseudotime$slingshot_umap_pca_orig)

anno <- anno[order(anno$Lineage2, decreasing = TRUE),]

expression <- expression[rownames(anno), c("174-HLADR", "151-CD123", "148-CD34")]

my_colour = list(metaclusters = c(HSCs = "#689030", pDCs = "#CD9BCD", `Pre-DC` = "#2B3990"))
```

```{r}
pheatmap(mat = expression, 
         scale = "column", 
         show_rownames = FALSE, 
         cluster_rows = F, 
         cluster_cols = F, 
         annotation_row = anno[, c("metaclusters", "Lineage2")], 
         annotation_colors = my_colour, 
         breaks = scaleColors(expression, maxvalue = 2)[["breaks"]], 
         color = scaleColors(expression, maxvalue = 2)[["color"]], 
         main = "Figure S6b - Heatmap pDCs trajectory")
```

## Monocytes
```{r}
selections <- rownames(condor_filter$clustering$Phenograph_filter_pca_orig_k_10[condor_filter$clustering$Phenograph_filter_pca_orig_k_10$metaclusters %in% c("HSCs", "CMPs", "Myeloblast", "Monocytes"), ])

condor_mono <- filter_fcd(fcdataset = condor_filter,
                            cell_ids = selections)
```

```{r}
expression <- condor_mono$expr$orig

anno <- cbind(condor_mono$clustering$Phenograph_filter_pca_orig_k_10[, c("Phenograph", "metaclusters")], condor_mono$pseudotime$slingshot_umap_pca_orig)

anno <- anno[order(anno$Lineage2, decreasing = FALSE),]

expression <- expression[rownames(anno), c("148-CD34", "160-CD14", "144-CD11b")]

my_colour = list(metaclusters = c(Monocytes = "#CBD588", HSCs = "#689030", Myeloblast = "#DA5724", CMPs = "#F7941D"))
```

```{r}
pheatmap(mat = expression, 
         scale = "column", 
         show_rownames = FALSE, 
         cluster_rows = F, 
         cluster_cols = F, 
         annotation_row = anno[, c("metaclusters", "Lineage2")], 
         annotation_colors = my_colour, 
         breaks = scaleColors(expression, maxvalue = 2)[["breaks"]], 
         color = scaleColors(expression, maxvalue = 2)[["color"]], main = "Figure 4f - Heatmap Monocytes pseudotime")
```

# Session Info
```{r}
info <- sessionInfo()

info
```
