---
title: "Figure 2.1 - Prepare Data Annotation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{condor_workflow}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  markdown: 
    wrap: 72
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Loading required packages

```{r setup, warning=F, message=F}
library(cyCONDOR, quietly = TRUE)
library(ggplot2)
library(ggsci)
library(dplyr)
library(ggpubr)
library(ggrastr)
library(RColorBrewer)
```

# Loading the data

```{r}
condor <- prep_fcd(data_path  = "./data/FC/", 
                    max_cell = 10000, 
                    useCSV = FALSE, 
                    transformation = "auto_logi", 
                    remove_param = c("FSC-H", "SSC-H", "FSC-W", "SSC-W", "Time", "live_dead"), 
                    anno_table = "./data/FC_metadata.csv", 
                    filename_col = "filename",
                    seed = 91, 
                    verbose = TRUE)
```

```{r}
class(condor)
```

# Pseudobulk PCA

```{r}
pb_PCA <- runPCA_pseudobulk(condor)
```

```{r, fig.height=5, fig.width=5}
ggplot(pb_PCA$pca, aes(x = PC1, y = PC2, color = group)) +
  geom_point(size = 7) +
  scale_color_manual(values = c("#BEBEBE", "#CE2827")) +
  theme_bw() + theme(aspect.ratio = 1) + ggtitle("Fig 2b Bulk PCA")
```

```{r, fig.height=5, fig.width=7}
tmp <- scale(pb_PCA$data)

tmp <- tmp[c("ID3.fcs", "ID5.fcs", "ID7.fcs", "ID6.fcs", "ID8.fcs", "ID10.fcs"),]

pheatmap::pheatmap(tmp, scale = "none", cluster_rows = FALSE, cluster_cols = TRUE,
                     breaks = cyCONDOR::scaleColors(data = tmp, maxvalue = NULL)[["breaks"]],
                     color = cyCONDOR::scaleColors(data = tmp, maxvalue = NULL)[["color"]],
                     main = "Fig 2c Pseudobulk marker heatmap", cellwidth = 15, cellheight = 15)
```


# Dimensionality Reduction

## PCA
```{r}
condor <- runPCA(fcd = condor, 
                 data_slot = "orig", 
                 seed = 91)
```

```{r, fig.height=5, fig.width=5}
plot_dim_red(fcd = condor, 
             expr_slot = "orig", 
             reduction_method = "pca", 
             reduction_slot = "orig", 
             cluster_slot = NULL,
             param = "group", 
             order = T, 
             title = "Figure s3b - UMAP group", 
             facet_by_variable = FALSE, 
             color_discrete = c("#BEBEBE", "#CE2827"), 
             raster = TRUE, 
             dot_size = 0.2, 
             alpha = 1)
```

```{r, fig.height=7, fig.width=7}
PC_loadings(fcd = condor, data_slot = "orig", nPC = 1)
```


## UMAP
```{r}
condor <- runUMAP(fcd = condor, 
                  input_type = "pca", 
                  data_slot = "orig", 
                  seed = 91)
```

### Rastered UMAP
```{r}
data <- cbind(condor$umap$pca_orig, condor$anno$cell_anno)
```

```{r, fig.height=5, fig.width=5}
plot_dim_red(fcd = condor, 
             expr_slot = "orig", 
             reduction_method = "umap", 
             reduction_slot = "pca_orig", 
             cluster_slot = NULL,
             param = "group", 
             order = T, 
             title = "Figure 2d - UMAP group", 
             facet_by_variable = FALSE, 
             color_discrete = c("#BEBEBE", "#CE2827"), 
             raster = TRUE)
```

```{r, fig.height=5, fig.width=8}
plot_dim_density(fcd = condor, 
                 reduction_method = "umap", 
                 reduction_slot = "pca_orig", 
                 group_var = "group", 
                 title = "Figure S2d - Density Map", 
                 dot_size = 0.2, 
                 alpha = 0.2, color_density = c("Greys", "Reds"))
```

## tSNE
```{r}
condor <- runtSNE(fcd = condor, 
                  input_type = "pca", 
                  data_slot = "orig", 
                  seed = 91, 
                  perplexity = 30)
```

# Clustering

## Phenograph
```{r}
condor <- runPhenograph(fcd = condor, 
                        input_type = "pca", 
                        data_slot = "orig", 
                        k = 60, 
                        seed = 91)
```

```{r, fig.height=5, fig.width=5}
plot_dim_red(fcd = condor, 
             expr_slot = "orig", 
             reduction_method = "umap", 
             reduction_slot = "pca_orig", 
             cluster_slot = "phenograph_pca_orig_k_60",
             param = "Phenograph", 
             order = T, 
             title = "Figure 2e - UMAP Phenograph clustering", 
             facet_by_variable = FALSE, 
             raster = TRUE, label_clusters = F)
```

```{r, fig.height=7, fig.width=7}
plot_marker_HM(fcd = condor, 
               expr_slot = "orig", 
               cluster_slot = "phenograph_pca_orig_k_60", 
               cluster_var = "Phenograph",
               maxvalue = 2, 
               marker_to_exclude = c("FSC-A", "SSC-A"),
               title = "Figure S3b - Marker expression Phenograph clustering", 
               cluster_rows = TRUE)
```

## FlowSOM
```{r}
condor <- runFlowSOM(fcd = condor, 
                     input_type = "pca", 
                     data_slot = "orig", 
                     nClusters = 15, 
                     seed = 91, 
                     prefix = NULL, 
                     ret_model = TRUE)
```

```{r, fig.height=5, fig.width=5}
plot_dim_red(fcd = condor, 
             expr_slot = "orig", 
             reduction_method = "umap", 
             reduction_slot = "pca_orig", 
             cluster_slot = "FlowSOM_pca_orig_k_15",
             param = "FlowSOM", 
             order = T, 
             title = "Figure S3c - UMAP FlowSOM Clustering", 
             facet_by_variable = FALSE, 
             raster = TRUE)
```

### Visualization of the SOM
```{r, fig.height=5, fig.width=5}
cluster_palette <- c("#89C5DA", "#DA5724", "#74D944", "#CE50CA", "#3F4921", "#C0717C", "#CBD588", "#5F7FC7",
                     "#673770", "#D3D93E", "#38333E", "#508578", "#D7C1B1", "#689030", "#AD6F3B", "#CD9BCD",
                     "#D14285", "#6DDE88", "#652926", "#7FDCC0", "#C84248", "#8569D5", "#5E738F", "#D1A33D",
                     "#8A7C64", "#599861", "#89C5DA", "#DA5724", "#74D944", "#CE50CA", "#3F4921", "#C0717C", "#CBD588", "#5F7FC7",
                     "#673770", "#D3D93E", "#38333E", "#508578", "#D7C1B1", "#689030", "#AD6F3B", "#CD9BCD",
                     "#D14285", "#6DDE88", "#652926", "#7FDCC0", "#C84248", "#8569D5", "#5E738F", "#D1A33D",
                     "#8A7C64", "#599861")

FlowSOM::PlotPies(condor$extras$FlowSOM_model, cellTypes = condor$clustering$FlowSOM_pca_orig_k_15$FlowSOM, colorPalette = cluster_palette) + ggtitle("Figure S3d - FlowSOM PiePlot")
```

```{r, fig.height=7, fig.width=7}
plot_marker_HM(fcd = condor, 
               expr_slot = "orig", 
               cluster_slot = "FlowSOM_pca_orig_k_15", 
               cluster_var = "FlowSOM",
               maxvalue = 2, 
               marker_to_exclude = c("FSC-A", "SSC-A"),
               title = "Figure S3e - Marker expression FlowSOM clustering", 
               cluster_rows = TRUE)
```

# Plot single markers - Figure S2e
```{r, fig.width=20, fig.height=20}
marker_exp_plot <- list()

for (marker in colnames(condor$expr$orig)[3:28]) {
  
  marker_exp_plot[[marker]] <- plot_dim_red(fcd = condor, 
                                            expr_slot = "orig", 
                                            reduction_method = "umap", 
                                            reduction_slot = "pca_orig", 
                                            cluster_slot = NULL,
                                            param = marker, 
                                            order = F, 
                                            title = marker, 
                                            facet_by_variable = FALSE, 
                                            raster = TRUE, 
                                            remove_guide = TRUE)
  
}

ggarrange(plotlist = marker_exp_plot)
```

# Metaclustering
```{r}
condor <- metaclustering(fcd = condor, 
                         cluster_slot = "phenograph_pca_orig_k_60",
                         cluster_var = "Phenograph", 
                         cluster_var_new = "metaclusters", 
                         metaclusters = c("1" = "Classical Monocytes",
                                          "2" = "CD4 CD45RA+ CD127+",
                                          "3" = "CD8 CD45RA+ CD127+", 
                                          "4" = "NK dim",
                                          "5" = "CD8 CD45RA+ CD127-",
                                          "6" = "Classical Monocytes",
                                          "7" = "Unconventional T cells", 
                                          "8" = "CD4 CD45RA- CD127+",
                                          "9" = "CD16+ Monocytes",
                                          "10" = "CD4 CD127-",
                                          "11" = "Classical Monocytes", 
                                          "12" = "CD8 CD45RA- CD127+", 
                                          "13" = "CD8 CD45RA- CD127+",
                                          "14" = "NK bright",
                                          "15" = "CD8 CD45RA+ CD127-",
                                          "16" = "CD4 CD25+",
                                          "17" = "B cells",
                                          "18" = "Unconventional T cells",
                                          "19" = "Classical Monocytes",
                                          "20" = "pDCs",
                                          "21" = "CD8 CD45RA+ CD127+",
                                          "22" = "Basophils",
                                          "23" = "Mixed",
                                          "24" = "B cells",
                                          "25" = "NK bright"))
```

```{r, fig.height=5, fig.width=5}
plot_dim_red(fcd = condor, 
             expr_slot = "orig", 
             reduction_method = "umap", 
             reduction_slot = "pca_orig", 
             cluster_slot = "phenograph_pca_orig_k_60",
             param = "metaclusters", 
             order = T, 
             title = "Figure 2f - UMAP Metaclustering", 
             facet_by_variable = FALSE, 
             raster = TRUE, 
             color_discrete = rev(cluster_palette), label_clusters = FALSE)
```

```{r, fig.height=7, fig.width=7}
plot_marker_HM(fcd = condor, 
               expr_slot = "orig", 
               cluster_slot = "phenograph_pca_orig_k_60", 
               cluster_var = "metaclusters",
               maxvalue = 2, 
               marker_to_exclude = c("FSC-A", "SSC-A"),
               title = "Figure 2f - Marker expression Metaclusters", 
               cluster_rows = TRUE)
```

# tSNE visualization clusters

```{r, fig.height=5, fig.width=5}
plot_dim_red(fcd = condor, 
             expr_slot = "orig", 
             reduction_method = "tSNE", 
             reduction_slot = "pca_orig", 
             cluster_slot = "phenograph_pca_orig_k_60",
             param = "Phenograph", 
             order = T, 
             title = "Figure S3a - tSNE Phenograph", 
             facet_by_variable = FALSE, 
             raster = TRUE)
```

# Session Info
```{r}
info <- sessionInfo()

info
```
