---
title: "Figure 2.3 - Spectral Flow example dataset"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{condor_workflow}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  markdown: 
    wrap: 72
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, warning=F, message=F}
library(cyCONDOR, quietly = T)
library(ggplot2)
library(ggsci)
library(dplyr)
library(ggpubr)
library(ggrastr)
```

# Loading the data

```{r, message=F}
condor <- prep_fcd(data_path = "./data/SF_fcs/", 
                    max_cell = 20000, 
                    useCSV = FALSE, 
                    transformation = "auto_logi", 
                    remove_param = c("FJComp-AF-A", "FJComp-LIVE DEAD Blue-A", "SSC-B-A", "SSC-B-H", "FSC-H", "SSC-H", "Time"), 
                    anno_table = "./data/SF_Multi_FR-FCM-Z4NB_cleaned.csv", 
                    filename_col = "filename",
                    seed = 91, 
                    verbose = TRUE)
```

```{r}
class(condor)
```

# Dimensionality Reduction

## PCA
```{r}
condor <- runPCA(fcd = condor, 
                 data_slot = "orig", 
                 seed = 91)
```

## UMAP
```{r}
condor <- runUMAP(fcd = condor, 
                  input_type = "pca", 
                  data_slot = "orig", 
                  seed = 91)
```

## tSNE
```{r}
condor <- runtSNE(fcd = condor, 
                  input_type = "pca", 
                  data_slot = "orig", 
                  seed = 91, 
                  perplexity = 30)
```

# Clustering

## Phenograph
```{r}
condor <- runPhenograph(fcd = condor, 
                        input_type = "pca", 
                        data_slot = "orig", 
                        k = 60, 
                        seed = 91)
```

```{r, fig.height=5, fig.width=5}
plot_dim_red(fcd = condor, 
             expr_slot = "orig", 
             reduction_method = "umap", 
             reduction_slot = "pca_orig", 
             cluster_slot = "phenograph_pca_orig_k_60",
             param = "Phenograph", 
             order = T, 
             title = "Figure 2h - UMAP Phenograph Clustering", 
             facet_by_variable = FALSE, 
             raster = TRUE)
```

```{r, fig.height=5, fig.width=5}
plot_dim_red(fcd = condor, 
             expr_slot = "orig", 
             reduction_method = "tSNE", 
             reduction_slot = "pca_orig", 
             cluster_slot = "phenograph_pca_orig_k_60",
             param = "Phenograph", 
             order = T, 
             title = "Figure S3h - tSNE Phenograph Clustering", 
             facet_by_variable = FALSE, 
             raster = TRUE)
```

```{r, fig.height=7, fig.width=7}
plot_marker_HM(fcd = condor, 
               expr_slot = "orig", 
               cluster_slot = "phenograph_pca_orig_k_60", 
               cluster_var = "Phenograph",
               maxvalue = 2, 
               title = "Figure S2i - Marker expression Phenograph clustering", 
               marker_to_exclude = c("SSC-A"),
               cluster_rows = TRUE, 
               cluster_cols = TRUE)
```

# Session Info
```{r}
info <- sessionInfo()

info
```
