---
title: "Figure 2.3 - Spectral Flow example dataset"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{condor_workflow}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  markdown: 
    wrap: 72
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
# library(condor, quietly = T)
library(ggplot2)
library(ggsci)
library(dplyr)
library(ggpubr)
library(ggrastr)
```

```{r}
cluster_palette <- c("#89C5DA", "#DA5724", "#74D944", "#CE50CA", "#3F4921", "#C0717C", "#CBD588", "#5F7FC7",
                     "#673770", "#D3D93E", "#38333E", "#508578", "#D7C1B1", "#689030", "#AD6F3B", "#CD9BCD",
                     "#D14285", "#6DDE88", "#652926", "#7FDCC0", "#C84248", "#8569D5", "#5E738F", "#D1A33D",
                     "#8A7C64", "#599861", "#89C5DA", "#DA5724", "#74D944", "#CE50CA", "#3F4921", "#C0717C", "#CBD588", "#5F7FC7",
                     "#673770", "#D3D93E", "#38333E", "#508578", "#D7C1B1", "#689030", "#AD6F3B", "#CD9BCD",
                     "#D14285", "#6DDE88", "#652926", "#7FDCC0", "#C84248", "#8569D5", "#5E738F", "#D1A33D",
                     "#8A7C64", "#599861")
```

# Loading the data

*Note* This script requires condor v015

```{r}
condor <- prep_fcd(FCSpath = "./data/CITE-seq/", 
                    ceil = 20000, 
                    useCSV = TRUE, 
                    transformation = "c", 
                    remove_param = c("InFile", "Time"), 
                    anno_table = "./data/CITE-seq.csv", 
                    filename_col = "filename", 
                    separator_fc_csv = ",",
                    seed = 91)
```

```{r}
class(condor)
```

# Dimensionality Reduction

## PCA
```{r}
condor <- runPCA(fcd = condor, 
                 data_slot = "orig", 
                 seed = 91)
```

## UMAP
```{r}
condor <- runUMAP(fcd = condor, 
                  input_type = "pca", 
                  data_slot = "orig", 
                  seed = 91)
```

## tSNE
```{r}
condor <- runtSNE(fcd = condor, 
                  input_type = "pca", 
                  data_slot = "orig", 
                  seed = 91, 
                  perplexity = 30)
```

# Clustering

## Phenograph
```{r}
condor <- runPhenograph(fcd = condor, 
                        input_type = "pca", 
                        data_slot = "orig", 
                        k = 30, 
                        seed = 91)
```

```{r}
plot_marker(data = cbind(condor$umap$pca_orig, condor$clustering$Phenograph_pca_orig_k_30), 
            param = "Phenograph", 
            order = T, 
            title = "Figure 2h - UMAP Phenograph Clustering", 
            dim_red = "UMAP", 
            facet_by_variable = FALSE, dot_size = 0.2, apha = 1)
```

```{r}
plot_marker(data = cbind(condor$tSNE$pca_orig, condor$clustering$Phenograph_pca_orig_k_30), 
            param = "Phenograph", 
            order = T, 
            title = "Figure S3h - tSNE Phenograph Clustering", 
            dim_red = "tSNE", 
            facet_by_variable = FALSE)
```

```{r}
data <- cbind(condor$umap$pca_orig, 
              condor$tSNE$pca_orig, 
              condor$anno$cell_anno, 
              Phenograph = condor$clustering$Phenograph_pca_orig_k_30[,1])
```

```{r}
ggplot(data = data, aes(x = UMAP1, y = UMAP2, color = Phenograph)) +
  geom_point_rast(alpha = 0.2, size = 0.1) +
  theme_bw() +
  theme(aspect.ratio = 1, panel.grid = element_blank()) +
  scale_color_manual(values = cluster_palette) + 
  guides(color = guide_legend(override.aes = list(size = 5, alpha = 1))) + 
  ggtitle("Figure 2h - UMAP Phenograph Clustering")
```

```{r}
ggplot(data = data, aes(x = tSNE1, y = tSNE2, color = Phenograph)) +
  geom_point_rast(alpha = 0.2, size = 0.1) +
  theme_bw() +
  theme(aspect.ratio = 1, panel.grid = element_blank()) +
  scale_color_manual(values = cluster_palette) + 
  guides(color = guide_legend(override.aes = list(size = 5, alpha = 1))) + 
  ggtitle("Figure S3h - tSNE Phenograph Clustering")
```

```{r, fig.height=7}
HM_markers(input = cbind(condor$expr$orig, condor$clustering$Phenograph_pca_orig_k_30), 
           group = "Phenograph",
           maxvalue = 2, 
           title = "Figure S2i - Marker expression Phenograph clustering", 
           cluster_rows = TRUE, cluster_cols = TRUE)
```

# All markers
```{r}
for (marker in colnames(condor$expr$orig)[1:30]) {
  
  plot(plot_marker(data = cbind(condor$umap$pca_orig, condor$expr$orig), 
                   param = marker, 
                   order = T, 
                   title = "Phenograph Clustering on Original expression", 
                   dim_red = "UMAP", facet_by_variable = FALSE, dot_size = 1, apha = 1))
  
}
```

```{r}
for (marker in colnames(condor$expr$orig)[1:30]) {
  
  plot(plot_marker(data = cbind(condor$tSNE$pca_orig, condor$expr$orig), 
                   param = marker, 
                   order = T, 
                   title = "Phenograph Clustering on Original expression", 
                   dim_red = "tSNE", facet_by_variable = FALSE, dot_size = 1, apha = 1))
  
}
```

# Session Info
```{r}
info <- sessionInfo()

info
```
