---
title: "Figure 7.1 - CytoDX example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{condor_workflow}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, message=F, warning=F}
library(cyCONDOR)
library(ggplot2)
library(ggpubr)
```

# Loading the data - Training Set

```{r}
condor <- prep_fcd(data_path = "/home/user/data/Data/Figure 7 - Clinical Classifier/data_and_envs/CytoDX/train/", 
                    max_cell = 10000000, 
                    useCSV = FALSE, 
                    transformation = "auto_logi", 
                    remove_param = c("FSC-A","FSC-W","FSC-H","Time"), 
                    anno_table = "/home/user/data/Data/Figure 7 - Clinical Classifier/data_and_envs/CytoDX/fcs_info_train.csv", 
                    filename_col = "fcsName",
                    seed = 91)
```

```{r}
class(condor)
```

## Visualize the data on a UMAP
```{r}
condor <- runPCA(fcd = condor, 
                 data_slot = "orig", 
                 seed = 91)
```

```{r}
condor <- runUMAP(fcd = condor, 
                  input_type = "pca", 
                  data_slot = "orig", 
                  seed = 91)
```

```{r, fig.height=5, fig.width=5}
plot_dim_red(fcd = condor, 
             expr_slot = "orig", 
             reduction_method = "umap", 
             reduction_slot = "pca_orig", 
             cluster_slot = NULL,
             param = "Label", 
             order = T, 
             title = "Figure 7b - UMAP training data", 
             facet_by_variable = FALSE, 
             color_discrete = c("#92278F", "#F15A29"), 
             raster = TRUE, 
             alpha = 1, 
             dot_size = 1)
```

## Build the classifier model
```{r}
# Re order variables

condor$anno$cell_anno$Label <- factor(condor$anno$cell_anno$Label, levels = c("normal", "aml"), labels = c("1_normal", "2_aml"))
```


```{r}
condor <- train_classifier_model(fcd = condor, 
                                 input_type = "expr", 
                                 data_slot = "orig", 
                                 sample_names = "expfcs_filename", 
                                 classification_variable = condor$anno$cell_anno$Label, 
                                 family = "binomial", 
                                 type1 = "response", 
                                 parallelCore = 1, 
                                 reg = FALSE, 
                                 seed = 91)
```

### Explore the model
```{r}
condor$extras$classifier_model$train.Data.sample

condor$extras$classifier_model$train.Data.cell[1:10,]
```


# Load the data - test Set

```{r}
condor_test <- prep_fcd(data_path = "/home/user/data/Data/Figure 7 - Clinical Classifier/data_and_envs/CytoDX/test/", 
                      max_cell = 10000000, 
                    useCSV = FALSE, 
                    transformation = "auto_logi", 
                    remove_param = c("FSC-A","FSC-W","FSC-H","Time"), 
                    anno_table = "/home/user/data/Data/Figure 7 - Clinical Classifier/data_and_envs/CytoDX/fcs_info_test.csv", 
                    filename_col = "fcsName",
                    seed = 91)
```

```{r}
class(condor_test)
```

## Predict classification
```{r}
# Re order variables

condor_test$anno$cell_anno$Label <- factor(condor_test$anno$cell_anno$Label, levels = c("normal", "aml"), labels = c("1_normal", "2_aml"))
```

```{r}
condor_test <- predict_classifier(fcd = condor_test, 
                                  input_type = "expr", 
                                  data_slot = "orig", 
                                  sample_names = "expfcs_filename", 
                                  model_object = condor$extras$classifier_model, 
                                  seed = 91)
```

### Explore Prediction
```{r}
condor_test$extras$classifier_prediction$xNew.Pred.sample

condor_test$extras$classifier_prediction$xNew.Pred.cell[1:10,]
```

# Visualize the results

## Training Data
```{r, fig.height=5, fig.width=5}
anno <- read.csv("/home/user/data/Data/Figure 7 - Clinical Classifier/data_and_envs/CytoDX/fcs_info_train.csv")

tmp <- merge(x = condor$extras$classifier_model$train.Data.cell, y = anno, by.x = "sample", by.y = "fcsName")

ggplot(tmp, aes(x = sample, y = y.Pred.s0, color = Label)) +
  geom_jitter() + 
  geom_violin() +
  scale_color_manual(values = c("#92278F", "#F15A29")) +
  theme_bw() + 
  theme(aspect.ratio = 1) + 
  ggtitle("Figure S12b - Training prediction cell")
```

```{r, fig.height=5, fig.width=5}
tmp <- merge(x = condor$extras$classifier_model$train.Data.sample, y = anno, by.x = "sample", by.y = "fcsName")

ggplot(tmp, aes(x = sample, y = y.Pred.s0, color = Label)) +
  geom_point(size = 4) +
  scale_color_manual(values = c("#92278F", "#F15A29")) +
  theme_bw() + 
  theme(aspect.ratio = 2) + 
  ggtitle("Figure S12c - Training prediction sample")
```

## Test Data
```{r, fig.height=5, fig.width=5}
anno <- read.csv("/home/user/data/Data/Figure 7 - Clinical Classifier/data_and_envs/CytoDX/fcs_info_test.csv")

tmp <- merge(x = condor_test$extras$classifier_prediction$xNew.Pred.cell, y = anno, by.x = "sample", by.y = "fcsName")

tmp$sample <- factor(tmp$sample, levels = c("sample1.fcs", "sample2.fcs", "sample3.fcs",  "sample4.fcs",  "sample5.fcs",  "sample6.fcs",  "sample7.fcs",  "sample8.fcs",  "sample9.fcs", "sample10.fcs"))

ggplot(tmp, aes(x = sample, y = y.Pred.s0, color = Label)) +
  geom_jitter() +
  geom_violin() +
  scale_color_manual(values = c("#92278F", "#F15A29")) +
  theme_bw() + 
  theme(aspect.ratio = 1) + 
  ggtitle("Figure 7c - Test prediction cell")
```

```{r, fig.height=5, fig.width=5}
tmp <- merge(x = condor_test$extras$classifier_prediction$xNew.Pred.sample, y = anno, by.x = "sample", by.y = "fcsName")

tmp$sample <- factor(tmp$sample, levels = c("sample1.fcs", "sample2.fcs", "sample3.fcs",  "sample4.fcs",  "sample5.fcs",  "sample6.fcs",  "sample7.fcs",  "sample8.fcs",  "sample9.fcs", "sample10.fcs"))

ggplot(tmp, aes(x = sample, y = y.Pred.s0, color = Label)) +
  geom_point(size = 4) +
  scale_color_manual(values = c("#92278F", "#F15A29")) +
  theme_bw() + 
  theme(aspect.ratio = 2) + 
  ggtitle("Figure 7d - Test prediction sample")
```

# Visualization of the decision three
```{r, fig.height=7, fig.width=7}
# Figure S12d - Decision tree

library(CytoDx)

treeGate(P = condor$extras$classifier_model$train.Data.cell$y.Pred.s0,
         x= condor$expr$orig)
```

# Session Info
```{r}
info <- sessionInfo()

info
```
